networks:
  api-net:
    name: api-net
    driver: bridge

volumes:
  db:
    name: db

services:
  db:
    container_name: db
    image: mongo
    restart: always
    networks:
      - api-net
    volumes:
      - db:/data/db      
  api:
    container_name: api
    image: joaoaaf/api-hackathon-itt
    restart: always
    ports:
      - 80:9080
    networks:
      - api-net
    depends_on:
      - db
    environment:
      MONGO_DB_HOST: db