name: Workflow CI/CD

on:
  push:
    branches:
      - main
env:
  TF_CLOUD_ORGANIZATION: "SOME-ORGANIZATION-MJ"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "SOME-PROJECT-MJ"
  CONFIG_DIRECTORY: "./terraform"
  # TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}

jobs:
  job_application_test_and_build:
    name: Test and build of application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Test
        run: go test -v

      - name: Build Application Go
        run: go build -v main.go

  job_image_build_and_push:

    needs:
      job_application_test_and_build

    name: Build and push of image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t joaoaaf/golang-api:1.0 .
          docker push joaoaaf/golang-api:1.0

  job_terraform_plan:
    needs:
      job_image_build_and_push

    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

  job_terraform_apply:
    needs:
      job_terraform_plan
    
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Apply Terraform
        run: terraform apply -auto-approve -input=false
