name: go

on:
  push:
    branches: 
      - main
jobs:
  job_application_test_and_build:
    name: Test and build of application
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Test
        run: go test -v
        
      - name: Build Application Go
        run: go build -v main.go
        
  job_image_build_and_push:
  
    needs:
      job_application_test_and_build
      
    name: Build and push of image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push image
        run: |
          docker build -t joaoaaf/golang-api:1.0 .
          docker push joaoaaf/golang-api:1.0
        

      ##########CREATE IMAGE##########
      # passo para subir do banco de dados por meio do docker compose
      #- name: Create DB
        #run: docker compose up -d
      # este passo executar치 os testes do c칩digo Go
      
      ##########DATABASE###
      #- name: Build DB
       # run: docker compose build
      # passo para subir do banco de dados por meio do docker compose
      #- name: Create DB
        #run: docker compose up -d
      # este passo executar치 os testes do c칩digo Go


