name: go

on:
  push:
    branches: 
      - main
jobs:
  go:
    name: deploy to production
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      ##########APPLICATION##########
      - name: Build Application Go
        run: go build -v main.go

      ##########TESTS##########
      - name: Test
        run: go test -v main_test.go
        
      ##########DATABASE##########
      #- name: Build DB
       # run: docker compose build
      # passo para subir do banco de dados por meio do docker compose
      #- name: Create DB
        #run: docker compose up -d
      # este passo executará os testes do código Go


